module.exports = {
  verbose: true,
  modulePaths: ["src"],
  moduleNameMapper: {
    "^Actions(.*)$": "<rootDir>/src/redux/actions$1",
    "^Assets(.*)$": "<rootDir>/src/assets$1",
    "^Components(.*)$": "<rootDir>/src/components$1",
    "^Constants(.*)$": "<rootDir>/src/constants$1",
    "^Containers(.*)$": "<rootDir>/src/containers$1",
    "^Reducers(.*)$": "<rootDir>/src/redux/reducers$1",
    "^Providers(.*)$": "<rootDir>/src/providers$1",
    "^Store(.*)$": "<rootDir>/src/store.js",
  },
  collectCoverageFrom: ["src/**/*.{js,jsx,ts,tsx}"],
  setupFiles: ["<rootDir>/config/polyfills.js", "<rootDir>/test/testSetup.js"],
  snapshotSerializers: ["./node_modules/enzyme-to-json/serializer"],
  testMatch: ["<rootDir>/src/**/__tests__/**/*.test.(js|tsx|ts|jsx)"],
  testEnvironment: "jsdom",
  testPathIgnorePatterns: ["<rootDir>/__e2e__/", "<rootDir>/node_modules/"],
  testURL: "http://localhost",
  transform: {
    "^.+\\.jsx?$": "babel-jest",
    "^.+\\.tsx?$": "ts-jest",
    "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
    "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js",
  },
  transformIgnorePatterns: ["[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"],
  moduleDirectories: ["node_modules"],
  moduleFileExtensions: [
    "web.js",
    "js",
    "json",
    "web.jsx",
    "jsx",
    "node",
    "ts",
    "tsx",
  ],
  globals: { window: true },
};
